spring:
    application:
        name: assets-service
    datasource:
        password: ${DATABASE_PASSWORD}
        username: ${DATABASE_USER}
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        show-sql: false
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                format_sql=true